/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tsk.mng.taskmanagement.usermanagementservice;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.tsk.mng.backend.infa.SpringInitializer;
import org.tsk.mng.backend.infa.TransformerUtil;
import org.tsk.mng.backend.model.UserBE;
import org.tsk.mng.backend.result.UserResultBE;
import org.tsk.mng.backend.service.UserManagementBEService;
import org.tsk.mng.frontend.Utils.TransformerFEvsBEUtil;
import org.tsk.mng.taskmanagement.common_elements.user.userfe.UserFE;
import org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult;

/**
 * This class was generated by Apache CXF 2.2 Fri Aug 17 16:25:01 IDT 2012
 * Generated source version: 2.2
 * 
 */

@javax.jws.WebService(serviceName = "UserManagementService", portName = "UserManagementServicePort", targetNamespace = "http://mng.tsk.org/taskManagement/UserManagementService/", wsdlLocation = "http://localhost:8080/TaskManagementService/services/UserManagementService?wsdl", endpointInterface = "org.tsk.mng.taskmanagement.usermanagementservice.UserManagementServicePortType")
public class UserManagementServicePortTypeImpl implements
		UserManagementServicePortType {

	private static final Logger LOG = Logger
			.getLogger(UserManagementServicePortTypeImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.tsk.mng.taskmanagement.usermanagementservice.
	 * UserManagementServicePortType
	 * #addSuperiorToUserOperation(org.tsk.mng.taskmanagement
	 * .header.soapheader.UserAuthInfo soapHeader
	 * ,)org.tsk.mng.taskmanagement.usermanagementwrapper
	 * .AddSuperiorToUserTypeRequest addSuperiorToUserRequest )*
	 */
	public org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult addSuperiorToUserOperation(
			org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo soapHeader,
			org.tsk.mng.taskmanagement.usermanagementwrapper.AddSuperiorToUserTypeRequest addSuperiorToUserRequest) {
		LOG.info("Executing operation addSuperiorToUserOperation");
		System.out.println(soapHeader);
		System.out.println(addSuperiorToUserRequest);
		try {
			org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.tsk.mng.taskmanagement.usermanagementservice.
	 * UserManagementServicePortType
	 * #createUserOperation(org.tsk.mng.taskmanagement
	 * .header.soapheader.UserAuthInfo soapHeader
	 * ,)org.tsk.mng.taskmanagement.usermanagementwrapper.CreateUserTypeRequest
	 * createUserRequest )*
	 */
	public org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult createUserOperation(
			org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo soapHeader,
			org.tsk.mng.taskmanagement.usermanagementwrapper.CreateUserTypeRequest createUserRequest) {
		LOG.info("Executing operation createUserOperation");
		System.out.println(soapHeader);
		System.out.println(createUserRequest);
		try {
			
			UserManagementBEService service = getUserService();//getting UserService
			
			UserFE userFE = createUserRequest.getUser();
			UserResultBE result = service.createUser(TransformerUtil.dozerConvert(userFE, UserBE.class));

			UserResult _return = TransformerUtil.dozerConvert(result, UserResult.class);
			
			return _return;
			
			
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.tsk.mng.taskmanagement.usermanagementservice.
	 * UserManagementServicePortType
	 * #deleteUserOperation(org.tsk.mng.taskmanagement
	 * .header.soapheader.UserAuthInfo soapHeader
	 * ,)org.tsk.mng.taskmanagement.usermanagementwrapper.DeleteUserTypeRequest
	 * deleteUserRequest )*
	 */
	public org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult deleteUserOperation(
			org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo soapHeader,
			org.tsk.mng.taskmanagement.usermanagementwrapper.DeleteUserTypeRequest deleteUserRequest) {
		LOG.info("Executing operation deleteUserOperation");
		System.out.println(soapHeader);
		System.out.println(deleteUserRequest);
		try {
			org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.tsk.mng.taskmanagement.usermanagementservice.
	 * UserManagementServicePortType
	 * #updateUserOperation(org.tsk.mng.taskmanagement
	 * .header.soapheader.UserAuthInfo soapHeader
	 * ,)org.tsk.mng.taskmanagement.usermanagementwrapper.UpdateUserTypeRequest
	 * updateUserRequest )*
	 */
	public org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult updateUserOperation(
			org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo soapHeader,
			org.tsk.mng.taskmanagement.usermanagementwrapper.UpdateUserTypeRequest updateUserRequest) {
		LOG.info("Executing operation updateUserOperation");
		System.out.println(soapHeader);
		System.out.println(updateUserRequest);
		try {
			org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.tsk.mng.taskmanagement.usermanagementservice.
	 * UserManagementServicePortType
	 * #readUserOperation(org.tsk.mng.taskmanagement
	 * .header.soapheader.UserAuthInfo soapHeader
	 * ,)org.tsk.mng.taskmanagement.usermanagementwrapper.ReadUserTypeRequest
	 * readUserRequest )*
	 */
	public org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult readUserOperation(
			org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo soapHeader,
			org.tsk.mng.taskmanagement.usermanagementwrapper.ReadUserTypeRequest readUserRequest) {
		LOG.info("Executing operation readUserOperation");

		try {

			UserManagementBEService service = getUserService();
			
			UserResultBE userResultBe = service.readUser(soapHeader.getUserName()); // TODO what about password?
			
			UserResult retValue = TransformerUtil.dozerConvert(userResultBe, UserResult.class);
			
			return retValue;

		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}
	
	private UserManagementBEService getUserService() {
		return SpringInitializer.getBean(UserManagementBEService.class);
	}

}
