
package org.tsk.mng.taskmanagement.usermanagementservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Aug 30 19:33:18 IDT 2012
 * Generated source version: 2.2
 * 
 */

public final class UserManagementServicePortType_UserManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://mng.tsk.org/taskManagement/UserManagementService/", "UserManagementService");

    private UserManagementServicePortType_UserManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = UserManagementService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UserManagementService ss = new UserManagementService(wsdlURL, SERVICE_NAME);
        UserManagementServicePortType port = ss.getUserManagementServicePort();  
        
        {
        System.out.println("Invoking addSuperiorToUserOperation...");
        org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo _addSuperiorToUserOperation_soapHeader = null;
        org.tsk.mng.taskmanagement.usermanagementwrapper.AddSuperiorToUserTypeRequest _addSuperiorToUserOperation_addSuperiorToUserRequest = null;
        org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _addSuperiorToUserOperation__return = port.addSuperiorToUserOperation(_addSuperiorToUserOperation_soapHeader, _addSuperiorToUserOperation_addSuperiorToUserRequest);
        System.out.println("addSuperiorToUserOperation.result=" + _addSuperiorToUserOperation__return);


        }
        {
        System.out.println("Invoking createUserOperation...");
        org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo _createUserOperation_soapHeader = null;
        org.tsk.mng.taskmanagement.usermanagementwrapper.CreateUserTypeRequest _createUserOperation_createUserRequest = null;
        org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _createUserOperation__return = port.createUserOperation(_createUserOperation_soapHeader, _createUserOperation_createUserRequest);
        System.out.println("createUserOperation.result=" + _createUserOperation__return);


        }
        {
        System.out.println("Invoking deleteUserOperation...");
        org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo _deleteUserOperation_soapHeader = null;
        org.tsk.mng.taskmanagement.usermanagementwrapper.DeleteUserTypeRequest _deleteUserOperation_deleteUserRequest = null;
        org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _deleteUserOperation__return = port.deleteUserOperation(_deleteUserOperation_soapHeader, _deleteUserOperation_deleteUserRequest);
        System.out.println("deleteUserOperation.result=" + _deleteUserOperation__return);


        }
        {
        System.out.println("Invoking updateUserOperation...");
        org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo _updateUserOperation_soapHeader = null;
        org.tsk.mng.taskmanagement.usermanagementwrapper.UpdateUserTypeRequest _updateUserOperation_updateUserRequest = null;
        org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _updateUserOperation__return = port.updateUserOperation(_updateUserOperation_soapHeader, _updateUserOperation_updateUserRequest);
        System.out.println("updateUserOperation.result=" + _updateUserOperation__return);


        }
        {
        System.out.println("Invoking readUserOperation...");
        org.tsk.mng.taskmanagement.header.soapheader.UserAuthInfo _readUserOperation_soapHeader = null;
        org.tsk.mng.taskmanagement.usermanagementwrapper.ReadUserTypeRequest _readUserOperation_readUserRequest = null;
        org.tsk.mng.taskmanagement.common_elements.user.userresult.UserResult _readUserOperation__return = port.readUserOperation(_readUserOperation_soapHeader, _readUserOperation_readUserRequest);
        System.out.println("readUserOperation.result=" + _readUserOperation__return);


        }

        System.exit(0);
    }

}
